Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using EasyOverTime.Models;
using System.Diagnostics;
using EasyOverTime.Auth;

namespace EasyOverTime.Controllers
{
    public class DashboardController : Controller
    {
   
        public IActionResult Dashboard()
        {
            return View("Index");
        }    

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/DashboardLogicController.cs
using Microsoft.AspNetCore.Mvc;
using EasyOverTime.Models;
using System.Diagnostics;
using EasyOverTime.Models.Form;
using Microsoft.AspNetCore.Authorization;
using System.Text;
using EasyOverTime.Auth;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;

namespace EasyOverTime.Controllers
{
    [Route("[controller]")]
    [ApiController]
    public class DashboardLogicController : Controller
    {
        private IConfiguration? _configuration;

		private ApplicationDbContext Context { get; }

        public DashboardLogicController(ApplicationDbContext _context, IConfiguration configuration)
        {
            this.Context = _context;
            _configuration = configuration;
		}

		[HttpPost]
        [Route("insertovertimedata")]
        //[ValidateAntiForgeryToken]
        public IActionResult OvertimeDataInsert([Bind] OvertimeFormModel Data)
        {
            try
            {
                var Name = Data.Name;
				var Branch = Data.Branch;
				var Position = Data.Position;
				var DateFiled = Data.DateFiled;
                var IdNumber = Data.IdNumber;

				if (ModelState.IsValid)
                {
                    if (IdNumber != 0)
                    {
                        Console.WriteLine(Data);
                        this.Context.Entry(Data).State = EntityState.Added;
                        this.Context.OvertimeForms.AddAsync(Data);
                        this.Context.SaveChanges();

                        var result = Json(new
                        {
                            idnumber = IdNumber,
                            name = Name,
                            branch = Branch,
                            position = Position,
                            datefiled = DateFiled,
                            message = "success",
                            status = "sucess"
                        });


                        return result;
                    }
                }

                var ErrorResult = Json(new
                {               
                    status = "Request not successful!"
                });
                return ErrorResult;

            }
            catch (DbUpdateConcurrencyException ex)
            {
                Console.WriteLine(ex.Message);
                return StatusCode(StatusCodes.Status404NotFound, ex.Message);
            }
        }

        [HttpPost]
        [Route("formdata")]
        public object OvertimeFormInsert(List<OvertimeData> Datas)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    //IList<OvertimeData> Data = new List<OvertimeData>()
                    //{
						
                    //     new OvertimeData{ IdNumber=Datas.IdNumber, Date="2020/4/23", TimeStart="5:00", TimeEnd="6:00", TotalNumberOfHours=1, Reason="as"},
                    //     new OvertimeData{ IdNumber=Datas.IdNumber, Date="2020/5/23", TimeStart="5:00", TimeEnd="6:00", TotalNumberOfHours=1, Reason="as"}

                    //};

                    if(Datas == null)
					{
                        Datas = new List<OvertimeData>();
					}
					else
					{
                        foreach (var Data in Datas)
                        {
                            this.Context.OvertimeDatas.AddRange(Data);

                        }
                        this.Context.SaveChanges();

                        var result = Json(new
                        {
                            message = "Successfully Added",
                            status = "sucess"
                        });

                        return result;
                    }      

                }

                return View();

            }
            catch (Exception ex)
            {
                return StatusCode(StatusCodes.Status404NotFound, ex.Message);
            }
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Dashboard/Data.cshtml
@model EasyOverTime.Models.Form.OvertimeData;
@*@model List<EasyOverTime.Models.Form.OvertimeData>;*@
<a class="btn-addnew btn-primary mb-2" id="addnew-data-button" href="">New</a>
<table class="table table-bordered" id="data-table">
	<thead class="p-5 thead" id="data-thead">
		<tr>
			<th>DATE</th>
			<th>TIME START</th>
			<th>TIME END</th>
			<th>TOTAL NO OF HOURS</th>
			<th>REASON</th>
			<th>DELETE</th>
		</tr>
	</thead>
	<tbody class="tableBody" id="tableBody">
	@*	if ( Model != null)
		{*@
			foreach (var data in Model)
			{
				<tr class="datas" id="table-datas">
					<td><input class="form-control" name="Date" id="date" asp-for="@Model.Date" type="date" /></td>
					<td><input class="form-control" name="TimeStart" id="time-start" asp-for="@Model.TimeStart" type="time" /></td>
					<td><input class="form-control" name="TimeEnd" id="time-out" asp-for="@Model.TimeEnd" type="time" /></td>
					<td><input class="form-control" name="TotalNumberOfHours" id="total-number-of-hours" asp-for="@Model.TotalNumberOfHours" type="number" /></td>
					<td><textarea class="form-control" name="Reason" id="reason" asp-for="@Model.Reason" rows="3"></textarea></td>
					<td id="deleteRow"></td>
				</tr>
			}
		@*}*@


	</tbody>
</table>

Views/Dashboard/Index.cshtml
@model EasyOverTime.Models.Form.OvertimeFormModel;
@{
}

<card class="card" id="dashboard-container">
	<center>
		<h3 class="card-title pt-4">Overtime Work Authorization Form</h3>
	</center>
	@*<form class="form m-5" method="post" asp-action="OvertimeFormInsert" asp-controller="Dashboard" autocomplete="off">*@

	<form class="form m-5" method="post" asp-action="OvertimeDataInsert" asp-controller="DashboardLogic" autocomplete="off">
		<div class="row mb-2">
			<div class="col-6">
				<label>ID NUMBER:</label>
				<input class="form-control" name="IdNumber" asp-for="@Model.IdNumber" id="id-number" type="number" />
			</div>			
		</div>

		<div class="row gy-2">
			<div class="col-6 form-floating">
				<input type="text" class="form-control" name="Name" asp-for="@Model.Name" id="Name" placeholder="Name">
				<label class="ms-3" for="Name">Name</label>
			</div>

			<div class="col-6 form-floating">
				<input type="text" class="form-control" name="Branch" asp-for="@Model.Branch" id="Branch" placeholder="Branch" />
				<label class="ms-3" for="Branch">Branch/division</label>
			</div>
		</div>
		<div class="row gy-3 mt-1">

			<div class="col-6 form-floating">
				<input type="text" class="form-control" name="Position" asp-for="@Model.Position" id="Position" placeholder="Position">
				<label class="ms-3" for="Position">Position</label>
			</div>

			<div class="col-6 form-floating">
				<input type="date" class="form-control" name="DateFiled" asp-for="@Model.DateFiled" id="DateFiled" placeholder="Date Filed" />
				<label class="ms-3" for="DateFiled">Date Filed</label>
			</div>
		</div>

		<div class="row mt-5 mb-5">
			<div class="col">
				<label>Regular OT:</label>
				<input type="checkbox" value="regular ot" id="Specification" asp-for="@Model.Specification" name="Specification"/>
			</div>

			<div class="col">
				<label>Restday OT:</label>
				<input type="checkbox" value="restdy ot" id="Specification" asp-for="@Model.Specification" name="Specification"/>
			</div>

			<div class="col">
				<label>Special Holiday OT:</label>
				<input type="checkbox" value="special holiday ot" id="Specification" asp-for="@Model.Specification" name="Specification"/>
			</div>

			<div class="col">
				<label>Legal Holiday OT:</label>
				<input type="checkbox" value="legal holiday ot" id="Specification" asp-for="@Model.Specification" name="Specification"/>
			</div>

			<div class="col">
				<label>Others:</label>
				<input type="checkbox" value="others" id="Specification" asp-for="@Model.Specification" name="Specification"/>
			</div>
		</div>
		
		<span id="status-message"></span>
		<partial name="Data"/>

		<div class="row">
			<div class="col-6">
				<label>TOTAL:</label>
				<input class="form-control" name="Total" id="Total" value="1" asp-for="@Model.Total" type="number" readonly />
			</div>

			<div class="col-6 d-flex">
				<button class="btn btn-primary mt-4 ms-auto" id="btn-dashboard" type="button">Submit</button>
			</div>
		</div>
		

	</form>

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js">
</script>
	<script type="text/javascript">

		$(document).ready(() => {
			$("#addnew-data-button").on('click',(e) => {
				e.preventDefault();
				let button = '<a id="newDeleteRow" href="">DELETE</a>';
				let newTable = $("#table-datas").clone();
				$(newTable).find("#deleteRow").append(button);
				$("#tableBody").append(newTable);
				newTable.addClass();
				return false;
			});

			$("#table-datas").on("click","#newDeleteRow" ,(e) => {
				e.preventDefault();
				$(this).parent().remove();
				return false;
			})

			$("#btn-dashboard").click(function () {
			let payloadForOverTimeForm = {
				"IdNumber":$("#id-number").val(),
				"Name": $("#Name").val(),
				"Total":$("#Total").val(),
				"Branch": $("#Branch").val(),
				"Position": $("#Position").val(),
				"DateFiled": $("#DateFiled").val(),
				"Specification": $("#Specification").val(),				
			};

			let payloadForOvertimeData = {
				"IdNumber":$("#id-number").val(),
				"Date": $("#date").val(),
				"TimeStart": $("#time-start").val(),
				"TimeEnd": $("#time-out").val(),
				"TotalNumberOfHours": $("#total-number-of-hours").val(),
				"Reason": $("#reason").val(),
			};

			console.log(payloadForOverTimeForm, "PAYLOADDDD1");
			console.log(payloadForOvertimeData, "PAYLOADDDD2");
			$.ajax({
				type:"POST",
				url:"/DashboardLogic/insertovertimedata",
				data: JSON.stringify(payloadForOverTimeForm),
				dataType: "json",
				contentType: "application/json",
				success: (result) => {
					console.log(result, "RESULTSSSS for insert prev data");

					if(result.status === "success"){
						$("#status-message").html(result.message);
					}else{
						$("#status-message").html("error while logging user!");
						window.location.href = "@Url.Action("Dashboard", "Dashboard")";
					}
				},
				error: () => {
					$("#status-message").html("Something went wrong!");
				}
			});


			$.ajax({
				type:"POST",
				url:"/DashboardLogic/formdata",
				data: JSON.stringify(payloadForOvertimeData),
				dataType: "json",
				contentType: "application/json",
				success: (result) => {
					console.log(result, "RESULTSSSS for form data");

					if(result.status === "success"){
						$("#status-message").html(result.message);
					}else{
						$("#status-message").html("error while logging user!");
						window.location.href = "@Url.Action("Dashboard", "Dashboard")";
					}
				},
				error: () => {
					$("#status-message").html("Something went wrong!");
				}
			});
			});
		});
	</script>
</card>